# Generated by Django 2.2.10 on 2020-02-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='skuXGB',
        ),
        migrations.AddField(
            model_name='datainfo',
            name='FLGB_data',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='LGB_data',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='XGB_data',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='real_data',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='skuID',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
