# Generated by Django 2.2.10 on 2020-02-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0003_auto_20200213_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='skuID',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
