# Generated by Django 2.2.10 on 2020-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0004_auto_20200213_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='FLR_data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='FXGB_data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='LR_data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='SVM_data',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
